import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  price,
  datetime,
  children
}: {
  price: React.ReactNode,
  datetime: React.ReactNode,
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main className="flex flex-col ">
        {datetime}
        {price}
        {children}
      </main>
      </body>
    </html>
  )
}
